baseURL = "https://isa-afp.org"
languageCode = "en-gb"
title = "Archive of Formal Proofs"
relativeURLs = true

[params]
description = """\
A collection of proof libraries, examples, and larger scientific developments, \
mechanically checked in the theorem prover Isabelle.\
"""
images = [ "/images/afp.png" ]
title = "Archive of Formal Proofs"
submissionUrl = "https://afp-submit.proof.cit.tum.de"

[params.afpUrls]
releases = "https://www.isa-afp.org/release"
html = "https://www.isa-afp.org/browser_info/current"
htmlDevel = "https://devel.isa-afp.org/browser_info/current"

[outputs]
home = [ "html", "rss" ]
page = [ "html" ]
section = []
taxonomy = []
term = []
